///////////////////////////////////////////////////////////
//  ActivityParameterNode.cs
//  Implementation of the Class ActivityParameterNode
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:52
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.Classification;

namespace UML.Activities
{
    /// <summary>
    ///     An ActivityParameterNode is an ObjectNode for accepting values from the input
    ///     Parameters or providing values to the output Parameters of an Activity.
    /// </summary>
    public interface ActivityParameterNode : ObjectNode
    {
        /// <summary>
        ///     The Parameter for which the ActivityParameterNode will be accepting or
        ///     providing values.
        /// </summary>
        Parameter parameter { get; set; }
    }
} //end namespace Activities