///////////////////////////////////////////////////////////
//  ActivityGroup.cs
//  Implementation of the Class ActivityGroup
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:52
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using UML.CommonStructure;

namespace UML.Activities
{
    /// <summary>
    ///     ActivityGroup is an class for defining sets of ActivityNodes and
    ///     ActivityEdges in an Activity.
    /// </summary>
    public interface ActivityGroup : NamedElement
    {
        /// <summary>
        ///     Other ActivityGroups immediately contained in this ActivityGroup.
        /// </summary>
        IEnumerable<ActivityGroup> subgroup { get; set; }

        /// <summary>
        ///     ActivityNodes immediately contained in the ActivityGroup.
        /// </summary>
        IEnumerable<ActivityNode> containedNode { get; set; }

        /// <summary>
        ///     ActivityEdges immediately contained in the ActivityGroup.
        /// </summary>
        IEnumerable<ActivityEdge> containedEdge { get; set; }

        /// <summary>
        ///     The Activity that directly or indirectly contains this ActivityGroup.
        /// </summary>
        /// <param name="result"></param>
        Activity containingActivity(Activity result);
    }
} //end namespace Activities