///////////////////////////////////////////////////////////
//  ActivityFinalNode.cs
//  Implementation of the Class ActivityFinalNode
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:52
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Activities
{
    /// <summary>
    ///     An ActivityFinalNode is a FinalNode that terminates the execution of its owning
    ///     Activity or StructuredActivityNode.
    /// </summary>
    public interface ActivityFinalNode : FinalNode
    {
    }
} //end namespace Activities