///////////////////////////////////////////////////////////
//  CentralBufferNode.cs
//  Implementation of the Class CentralBufferNode
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:54
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Activities
{
    /// <summary>
    ///     A CentralBufferNode is an ObjectNode for managing flows from multiple sources
    ///     and targets.
    /// </summary>
    public interface CentralBufferNode : ObjectNode
    {
    }
} //end namespace Activities