///////////////////////////////////////////////////////////
//  ControlFlow.cs
//  Implementation of the Class ControlFlow
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:57
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Activities
{
    /// <summary>
    ///     A ControlFlow is an ActivityEdge traversed by control tokens or object tokens
    ///     of control type, which are use to control the execution of ExecutableNodes.
    /// </summary>
    public interface ControlFlow : ActivityEdge
    {
    }
} //end namespace Activities