///////////////////////////////////////////////////////////
//  ControlNode.cs
//  Implementation of the Class ControlNode
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:57
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Activities
{
    /// <summary>
    ///     A ControlNode is an ActivityNode that coordinates flows in an Activity.
    /// </summary>
    public interface ControlNode : ActivityNode
    {
    }
} //end namespace Activities