///////////////////////////////////////////////////////////
//  DataStoreNode.cs
//  Implementation of the Class DataStoreNode
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:57
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Activities
{
    /// <summary>
    ///     A DataStoreNode is a CentralBufferNode for persistent data.
    /// </summary>
    public interface DataStoreNode : CentralBufferNode
    {
    }
} //end namespace Activities