///////////////////////////////////////////////////////////
//  DecisionNode.cs
//  Implementation of the Class DecisionNode
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:58
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.CommonBehavior;

namespace UML.Activities
{
    /// <summary>
    ///     A DecisionNode is a ControlNode that chooses between outgoing ActivityEdges for
    ///     the routing of tokens.
    /// </summary>
    public interface DecisionNode : ControlNode
    {
        /// <summary>
        ///     An additional ActivityEdge incoming to the DecisionNode that provides a
        ///     decision input value for the guards ValueSpecifications on ActivityEdges
        ///     outgoing from the DecisionNode.
        /// </summary>
        ObjectFlow decisionInputFlow { get; set; }

        /// <summary>
        ///     A Behavior that is executed to provide an input to guard ValueSpecifications on
        ///     ActivityEdges outgoing from the DecisionNode.
        /// </summary>
        Behavior decisionInput { get; set; }
    }
} //end namespace Activities