///////////////////////////////////////////////////////////
//  ExecutableNode.cs
//  Implementation of the Class ExecutableNode
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:00
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;

namespace UML.Activities
{
    /// <summary>
    ///     An ExecutableNode is an class for ActivityNodes whose execution may be
    ///     controlled using ControlFlows and to which ExceptionHandlers may be attached.
    /// </summary>
    public interface ExecutableNode : ActivityNode
    {
        /// <summary>
        ///     A set of ExceptionHandlers that are examined if an exception propagates out of
        ///     the ExceptionNode.
        /// </summary>
        IEnumerable<ExceptionHandler> handler { get; set; }
    }
} //end namespace Activities