///////////////////////////////////////////////////////////
//  FinalNode.cs
//  Implementation of the Class FinalNode
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:01
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Activities
{
    /// <summary>
    ///     A FinalNode is an ControlNode at which a flow in an Activity stops.
    /// </summary>
    public interface FinalNode : ControlNode
    {
    }
} //end namespace Activities