///////////////////////////////////////////////////////////
//  FlowFinalNode.cs
//  Implementation of the Class FlowFinalNode
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:01
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Activities
{
    /// <summary>
    ///     A FlowFinalNode is a FinalNode that terminates a flow by consuming the tokens
    ///     offered to it.
    /// </summary>
    public interface FlowFinalNode : FinalNode
    {
    }
} //end namespace Activities