///////////////////////////////////////////////////////////
//  ForkNode.cs
//  Implementation of the Class ForkNode
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:02
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Activities
{
    /// <summary>
    ///     A ForkNode is a ControlNode that splits a flow into multiple concurrent flows.
    /// </summary>
    public interface ForkNode : ControlNode
    {
    }
} //end namespace Activities