///////////////////////////////////////////////////////////
//  InitialNode.cs
//  Implementation of the Class InitialNode
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:03
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Activities
{
    /// <summary>
    ///     An InitialNode is a ControlNode that offers a single control token when
    ///     initially enabled.
    /// </summary>
    public interface InitialNode : ControlNode
    {
    }
} //end namespace Activities