///////////////////////////////////////////////////////////
//  InterruptibleActivityRegion.cs
//  Implementation of the Class InterruptibleActivityRegion
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:04
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;

namespace UML.Activities
{
    /// <summary>
    ///     An InterruptibleActivityRegion is an ActivityGroup that supports the
    ///     termination of tokens flowing in the portions of an activity within it.
    /// </summary>
    public interface InterruptibleActivityRegion : ActivityGroup
    {
        /// <summary>
        ///     ActivityNodes immediately contained in the InterruptibleActivityRegion.
        /// </summary>
        IEnumerable<ActivityNode> node { get; set; }

        /// <summary>
        ///     The ActivityEdges leaving the InterruptibleActivityRegion on which a traversing
        ///     token will result in the termination of other tokens flowing in the
        ///     InterruptibleActivityRegion.
        /// </summary>
        IEnumerable<ActivityEdge> interruptingEdge { get; set; }
    }
} //end namespace Activities