///////////////////////////////////////////////////////////
//  JoinNode.cs
//  Implementation of the Class JoinNode
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:04
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.Values;

namespace UML.Activities
{
    /// <summary>
    ///     A JoinNode is a ControlNode that synchronizes multiple flows.
    /// </summary>
    public interface JoinNode : ControlNode
    {
        /// <summary>
        ///     Indicates whether incoming tokens having objects with the same identity are
        ///     combined into one by the JoinNode.
        /// </summary>
        bool isCombineDuplicate { get; set; }

        /// <summary>
        ///     A ValueSpecification giving the condition under which the JoinNode will offer a
        ///     token on its outgoing ActivityEdge. If no joinSpec is specified, then the
        ///     JoinNode will offer an outgoing token if tokens are offered on all of its
        ///     incoming ActivityEdges (an "and" condition).
        /// </summary>
        ValueSpecification joinSpec { get; set; }
    }
} //end namespace Activities