///////////////////////////////////////////////////////////
//  MergeNode.cs
//  Implementation of the Class MergeNode
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:06
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Activities
{
    /// <summary>
    ///     A merge node is a control node that brings together multiple alternate flows.
    ///     It is not used to synchronize concurrent flows but to accept one among several
    ///     alternate flows.
    /// </summary>
    public interface MergeNode : ControlNode
    {
    }
} //end namespace Activities