///////////////////////////////////////////////////////////
//  ObjectNodeOrderingKind.cs
//  Implementation of the Enumeration ObjectNodeOrderingKind
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:07
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Activities
{
    /// <summary>
    ///     ObjectNodeOrderingKind is an enumeration indicating queuing order for offering
    ///     the tokens held by an ObjectNode.
    /// </summary>
    public enum ObjectNodeOrderingKind
    {
        /// <summary>
        ///     Indicates that tokens are unordered.
        /// </summary>
        unordered,

        /// <summary>
        ///     Indicates that tokens are ordered.
        /// </summary>
        ordered,

        /// <summary>
        ///     Indicates that tokens are queued in a last in, first out manner.
        /// </summary>
        LIFO,

        /// <summary>
        ///     Indicates that tokens are queued in a first in, first out manner.
        /// </summary>
        FIFO
    } //end ObjectNodeOrderingKind
} //end namespace Activities