///////////////////////////////////////////////////////////
//  ObjectFlow.cs
//  Implementation of the Class ObjectFlow
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:07
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.CommonBehavior;

namespace UML.Activities
{
    /// <summary>
    ///     An ObjectFlow is an ActivityEdge that is traversed by object tokens that may
    ///     hold values. Object flows also support multicast/receive, token selection from
    ///     object nodes, and transformation of tokens.
    /// </summary>
    public interface ObjectFlow : ActivityEdge
    {
        /// <summary>
        ///     Indicates whether the objects in the ObjectFlow are passed by multicasting.
        /// </summary>
        bool isMulticast { get; set; }

        /// <summary>
        ///     Indicates whether the objects in the ObjectFlow are gathered from respondents
        ///     to multicasting.
        /// </summary>
        bool isMultireceive { get; set; }

        /// <summary>
        ///     A Behavior used to select tokens from a source ObjectNode.
        /// </summary>
        Behavior selection { get; set; }

        /// <summary>
        ///     A Behavior used to change or replace object tokens flowing along the ObjectFlow.
        /// </summary>
        Behavior transformation { get; set; }
    }
} //end namespace Activities