///////////////////////////////////////////////////////////
//  Variable.cs
//  Implementation of the Class Variable
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:18
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.Actions;
using UML.CommonStructure;
using UML.StructuredClassifiers;

namespace UML.Activities
{
    /// <summary>
    ///     A Variable is a ConnectableElement that may store values during the execution
    ///     of an Activity. Reading and writing the values of a Variable provides an
    ///     alternative means for passing data than the use of ObjectFlows. A Variable may
    ///     be owned directly by an Activity, in which case it is accessible from anywhere
    ///     within that activity, or it may be owned by a StructuredActivityNode, in which
    ///     case it is only accessible within that node.
    /// </summary>
    public interface Variable : MultiplicityElement, ConnectableElement
    {
        /// <summary>
        ///     A Variable is accessible by Actions within its scope (the Activity or
        ///     StructuredActivityNode that owns it).
        /// </summary>
        /// <param name="result"></param>
        /// <param name="a"></param>
        bool isAccessibleBy(Action a);
    }
} //end namespace Activities