///////////////////////////////////////////////////////////
//  ActionExecutionSpecification.cs
//  Implementation of the Class ActionExecutionSpecification
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:52
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.Actions;

namespace UML.Interactions
{
    /// <summary>
    ///     An ActionExecutionSpecification is a kind of ExecutionSpecification
    ///     representing the execution of an Action.
    /// </summary>
    public interface ActionExecutionSpecification : ExecutionSpecification
    {
        /// <summary>
        ///     Action whose execution is occurring.
        /// </summary>
        Action action { get; set; }
    }
} //end namespace Interactions