///////////////////////////////////////////////////////////
//  CombinedFragment.cs
//  Implementation of the Class CombinedFragment
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:55
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;

namespace UML.Interactions
{
    /// <summary>
    ///     A CombinedFragment defines an expression of InteractionFragments. A
    ///     CombinedFragment is defined by an interaction operator and corresponding
    ///     InteractionOperands. Through the use of CombinedFragments the user will be able
    ///     to describe a number of traces in a compact and concise manner.
    /// </summary>
    public interface CombinedFragment : InteractionFragment
    {
        /// <summary>
        ///     Specifies the operation which defines the semantics of this combination of
        ///     InteractionFragments.
        /// </summary>
        InteractionOperatorKind interactionOperator { get; set; }

        /// <summary>
        ///     The set of operands of the combined fragment.
        /// </summary>
        InteractionOperand operand { get; set; }

        /// <summary>
        ///     Specifies the gates that form the public interface between this CombinedFragment and
        ///     its surroundings
        /// </summary>
        IEnumerable<Gate> cfragmentGate { get; set; }
    }
} //end namespace Interactions