///////////////////////////////////////////////////////////
//  ConsiderIgnoreFragment.cs
//  Implementation of the Class ConsiderIgnoreFragment
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:57
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using UML.CommonStructure;

namespace UML.Interactions
{
    /// <summary>
    ///     A ConsiderIgnoreFragment is a kind of CombinedFragment that is used for the
    ///     consider and ignore cases, which require lists of pertinent Messages to be
    ///     specified.
    /// </summary>
    public interface ConsiderIgnoreFragment : CombinedFragment
    {
        /// <summary>
        ///     The set of messages that apply to this fragment.
        /// </summary>
        IEnumerable<NamedElement> message { get; set; }
    }
} //end namespace Interactions