///////////////////////////////////////////////////////////
//  Continuation.cs
//  Implementation of the Class Continuation
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:57
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Interactions
{
    /// <summary>
    ///     A Continuation is a syntactic way to define continuations of different branches
    ///     of an alternative CombinedFragment. Continuations are intuitively similar to
    ///     labels representing intermediate points in a flow of control.
    /// </summary>
    public interface Continuation : InteractionFragment
    {
        /// <summary>
        ///     True: when the Continuation is at the end of the enclosing InteractionFragment
        ///     and False when it is in the beginning.
        /// </summary>
        bool setting { get; set; }
    }
} //end namespace Interactions