///////////////////////////////////////////////////////////
//  DestructionOccurrenceSpecification.cs
//  Implementation of the Class DestructionOccurrenceSpecification
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:58
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Interactions
{
    /// <summary>
    ///     A DestructionOccurenceSpecification models the destruction of an object.
    /// </summary>
    public interface DestructionOccurrenceSpecification : MessageOccurrenceSpecification
    {
    }
} //end namespace Interactions