///////////////////////////////////////////////////////////
//  ExecutionSpecification.cs
//  Implementation of the Class ExecutionSpecification
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:00
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Interactions
{
    /// <summary>
    ///     An ExecutionSpecification is a specification of the execution of a unit of
    ///     Behavior or Action within the Lifeline. The duration of an
    ///     ExecutionSpecification is represented by two OccurrenceSpecifications, the
    ///     start OccurrenceSpecification and the finish OccurrenceSpecification.
    /// </summary>
    public interface ExecutionSpecification : InteractionFragment
    {
        /// <summary>
        ///     References the OccurrenceSpecification that designates the start of the Action
        ///     or Behavior.
        /// </summary>
        OccurrenceSpecification start { get; set; }

        /// <summary>
        ///     References the OccurrenceSpecification that designates the finish of the Action
        ///     or Behavior.
        /// </summary>
        OccurrenceSpecification finish { get; set; }
    }
} //end namespace Interactions