///////////////////////////////////////////////////////////
//  ExecutionOccurrenceSpecification.cs
//  Implementation of the Class ExecutionOccurrenceSpecification
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:00
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Interactions
{
    /// <summary>
    ///     An ExecutionOccurrenceSpecification represents moments in time at which Actions
    ///     or Behaviors start or finish.
    /// </summary>
    public interface ExecutionOccurrenceSpecification : OccurrenceSpecification
    {
        /// <summary>
        ///     References the execution specification describing the execution that is started
        ///     or finished at this execution event.
        /// </summary>
        ExecutionSpecification execution { get; set; }
    }
} //end namespace Interactions