///////////////////////////////////////////////////////////
//  GeneralOrdering.cs
//  Implementation of the Class GeneralOrdering
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:02
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.CommonStructure;

namespace UML.Interactions
{
    /// <summary>
    ///     A GeneralOrdering represents a binary relation between two
    ///     OccurrenceSpecifications, to describe that one OccurrenceSpecification must
    ///     occur before the other in a valid trace. This mechanism provides the ability to
    ///     define partial orders of OccurrenceSpecifications that may otherwise not have a
    ///     specified order.
    /// </summary>
    public interface GeneralOrdering : NamedElement
    {
        /// <summary>
        ///     The OccurrenceSpecification referenced comes before the OccurrenceSpecification
        ///     referenced by after.
        /// </summary>
        OccurrenceSpecification before { get; set; }

        /// <summary>
        ///     The OccurrenceSpecification referenced comes after the OccurrenceSpecification
        ///     referenced by before.
        /// </summary>
        OccurrenceSpecification after { get; set; }
    }
} //end namespace Interactions