///////////////////////////////////////////////////////////
//  InteractionConstraint.cs
//  Implementation of the Class InteractionConstraint
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:03
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.CommonStructure;
using UML.Values;

namespace UML.Interactions
{
    /// <summary>
    ///     An InteractionConstraint is a Boolean expression that guards an operand in a
    ///     CombinedFragment.
    /// </summary>
    public interface InteractionConstraint : Constraint
    {
        /// <summary>
        ///     The maximum number of iterations of a loop
        /// </summary>
        ValueSpecification maxint { get; set; }

        /// <summary>
        ///     The minimum number of iterations of a loop
        /// </summary>
        ValueSpecification minint { get; set; }
    }
} //end namespace Interactions