///////////////////////////////////////////////////////////
//  InteractionUse.cs
//  Implementation of the Class InteractionUse
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:04
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using UML.Classification;
using UML.Values;

namespace UML.Interactions
{
    /// <summary>
    ///     An InteractionUse refers to an Interaction. The InteractionUse is a shorthand
    ///     for copying the contents of the referenced Interaction where the InteractionUse
    ///     is. To be accurate the copying must take into account substituting parameters
    ///     with arguments and connect the formal Gates with the actual ones.
    /// </summary>
    public interface InteractionUse : InteractionFragment
    {
        /// <summary>
        ///     The actual gates of the InteractionUse.
        /// </summary>
        IEnumerable<Gate> actualGate { get; set; }

        /// <summary>
        ///     The actual arguments of the Interaction.
        /// </summary>
        IEnumerable<ValueSpecification> argument { get; set; }

        /// <summary>
        ///     The value of the executed Interaction.
        /// </summary>
        ValueSpecification returnValue { get; set; }

        /// <summary>
        ///     Refers to the Interaction that defines its meaning.
        /// </summary>
        Interaction refersTo { get; set; }

        /// <summary>
        ///     The recipient of the return value.
        /// </summary>
        Property returnValueRecipient { get; set; }
    }
} //end namespace Interactions