///////////////////////////////////////////////////////////
//  InteractionOperand.cs
//  Implementation of the Class InteractionOperand
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:03
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using UML.CommonStructure;

namespace UML.Interactions
{
    /// <summary>
    ///     An InteractionOperand is contained in a CombinedFragment. An InteractionOperand
    ///     represents one operand of the expression given by the enclosing
    ///     CombinedFragment.
    /// </summary>
    public interface InteractionOperand : Namespace, InteractionFragment
    {
        /// <summary>
        ///     Constraint of the operand.
        /// </summary>
        InteractionConstraint guard { get; set; }

        /// <summary>
        ///     The fragments of the operand.
        /// </summary>
        IEnumerable<InteractionFragment> fragment { get; set; }
    }
} //end namespace Interactions