///////////////////////////////////////////////////////////
//  MessageEnd.cs
//  Implementation of the Class MessageEnd
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:06
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.CommonStructure;

namespace UML.Interactions
{
    /// <summary>
    ///     MessageEnd is an specialization of NamedElement that represents what
    ///     can occur at the end of a Message.
    /// </summary>
    public interface MessageEnd : NamedElement
    {
        /// <summary>
        ///     References a Message.
        /// </summary>
        Message message { get; set; }

        /// <summary>
        /// This query returns a set including the enclosing InteractionFragment this
        /// MessageEnd is enclosed within.
        /// </summary>
        /// <param name="result"></param>
        //InteractionFragment enclosingFragment(InteractionFragment result){

        //	return null;
        //}

        /// <summary>
        /// This query returns value true if this MessageEnd is a receiveEvent.
        /// </summary>
        /// <param name="result"></param>
        //void isReceive(result){

        //}

        /// <summary>
        /// This query returns value true if this MessageEnd is a sendEvent.
        /// </summary>
        /// <param name="result"></param>
        //void isSend(result){

        //}

        /// <summary>
        /// This query returns a set including the MessageEnd (if exists) at the opposite
        /// end of the Message for this MessageEnd.
        /// </summary>
        /// <param name="result"></param>
        //MessageEnd oppositeEnd(MessageEnd result){

        //	return null;
        //}
    }
} //end namespace Interactions