///////////////////////////////////////////////////////////
//  MessageKind.cs
//  Implementation of the Enumeration MessageKind
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:06
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Interactions
{
    /// <summary>
    ///     This is an enumerated type that identifies the type of Message.
    /// </summary>
    public enum MessageKind
    {
        /// <summary>
        ///     sendEvent and receiveEvent are present
        /// </summary>
        complete,

        /// <summary>
        ///     sendEvent present and receiveEvent absent
        /// </summary>
        lost,

        /// <summary>
        ///     sendEvent absent and receiveEvent present
        /// </summary>
        found,

        /// <summary>
        ///     sendEvent and receiveEvent absent (should not appear)
        /// </summary>
        unknown
    } //end MessageKind
} //end namespace Interactions