///////////////////////////////////////////////////////////
//  MessageOccurrenceSpecification.cs
//  Implementation of the Class MessageOccurrenceSpecification
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:06
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Interactions
{
    /// <summary>
    ///     A MessageOccurrenceSpecification specifies the occurrence of Message events,
    ///     such as sending and receiving of Signals or invoking or receiving of Operation
    ///     calls. A MessageOccurrenceSpecification is a kind of MessageEnd. Messages are
    ///     generated either by synchronous Operation calls or asynchronous Signal sends.
    ///     They are received by the execution of corresponding AcceptEventActions.
    /// </summary>
    public interface MessageOccurrenceSpecification : OccurrenceSpecification, MessageEnd
    {
    }
} //end namespace Interactions