///////////////////////////////////////////////////////////
//  PartDecomposition.cs
//  Implementation of the Class PartDecomposition
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:09
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Interactions
{
    /// <summary>
    ///     A PartDecomposition is a description of the internal Interactions of one
    ///     Lifeline relative to an Interaction.
    /// </summary>
    public interface PartDecomposition : InteractionUse
    {
    }
} //end namespace Interactions