///////////////////////////////////////////////////////////
//  StateInvariant.cs
//  Implementation of the Class StateInvariant
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:14
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.CommonStructure;

namespace UML.Interactions
{
    /// <summary>
    ///     A StateInvariant is a runtime constraint on the participants of the Interaction.
    ///     It may be used to specify a variety of different kinds of Constraints, such as
    ///     values of Attributes or Variables, internal or external States, and so on. A
    ///     StateInvariant is an InteractionFragment and it is placed on a Lifeline.
    /// </summary>
    public interface StateInvariant : InteractionFragment
    {
        /// <summary>
        ///     References the Lifeline on which the StateInvariant appears.
        /// </summary>
        Lifeline covered { get; set; }

        /// <summary>
        ///     A Constraint that should hold at runtime for this StateInvariant.
        /// </summary>
        Constraint invariant { get; set; }
    }
} //end namespace Interactions