///////////////////////////////////////////////////////////
//  Comment.cs
//  Implementation of the Class Comment
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:56
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;

namespace UML.CommonStructure
{
    /// <summary>
    ///     A Comment is a textual annotation that can be attached to a set of Elements.
    /// </summary>
    public interface Comment : Element
    {
        /// <summary>
        ///     Specifies a string that is the comment.
        /// </summary>
        string Body { get; set; }

        /// <summary>
        ///     References the Element(s) being commented.
        /// </summary>
        IEnumerable<Element> AnnotatedElements { get; set; }
    }
} //end namespace CommonStructure