///////////////////////////////////////////////////////////
//  Element.cs
//  Implementation of the Class Element
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:59
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;

namespace UML.CommonStructure
{
    /// <summary>
    ///     An Element is a constituent of a model. As such, it has the capability of
    ///     owning other Elements.
    /// </summary>
    public interface Element
    {
        /// <summary>
        ///     The Comments owned by this Element.
        /// </summary>
        IEnumerable<Comment> ownedComments { get; set; }

        /// <summary>
        ///     The Elements owned by this Element.
        /// </summary>
        IEnumerable<Element> ownedElement { get; set; }

        /// <summary>
        ///     The query allOwnedElements() gives all of the direct and indirect ownedElements
        ///     of an Element.
        /// </summary>
        /// <param name="result"></param>
        Element allOwnedElements(Element result);

        /// <summary>
        ///     The query mustBeOwned() indicates whether Elements of this type must have an
        ///     owner. Subclasses of Element that do not require an owner must override this
        ///     operation.
        /// </summary>
        /// <param name="result"></param>
        bool mustBeOwned();
    }
} //end namespace CommonStructure