///////////////////////////////////////////////////////////
//  PackageImport.cs
//  Implementation of the Class PackageImport
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:09
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.Packages;

namespace UML.CommonStructure
{
    /// <summary>
    ///     A PackageImport is a Relationship that imports all the non-private members of a
    ///     Package into the Namespace owning the PackageImport, so that those Elements may
    ///     be referred to by their unqualified names in the importingNamespace.
    /// </summary>
    public interface PackageImport : DirectedRelationship
    {
        /// <summary>
        ///     Specifies the visibility of the imported PackageableElements within the
        ///     importingNamespace, i.e., whether imported Elements will in turn be visible to
        ///     other Namespaces. If the PackageImport is public, the imported Elements will be
        ///     visible outside the importingNamespace, while, if the PackageImport is private,
        ///     they will not.
        /// </summary>
        VisibilityKind visibility { get; set; }

        /// <summary>
        ///     Specifies the Package whose members are imported into a Namespace.
        /// </summary>
        Package importedPackage { get; set; }
    }
} //end namespace CommonStructure