///////////////////////////////////////////////////////////
//  PackageableElement.cs
//  Implementation of the Class PackageableElement
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:09
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.CommonStructure
{
    /// <summary>
    ///     A PackageableElement is a NamedElement that may be owned directly by a Package.
    ///     A PackageableElement is also able to serve as the parameteredElement of a
    ///     TemplateParameter.
    /// </summary>
    public interface PackageableElement : NamedElement, ParameterableElement
    {
        /// <summary>
        ///     A PackageableElement must have a visibility specified if it is owned by a
        ///     Namespace. The default visibility is public.
        /// </summary>
        VisibilityKind visibility { get; set; }
    }
} //end namespace CommonStructure