///////////////////////////////////////////////////////////
//  ParameterableElement.cs
//  Implementation of the Class ParameterableElement
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:09
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.CommonStructure
{
    /// <summary>
    ///     A ParameterableElement is an Element that can be exposed as a formal
    ///     TemplateParameter for a template, or specified as an actual parameter in a
    ///     binding of a template.
    /// </summary>
    public interface ParameterableElement : Element
    {
        /// <summary>
        ///     The TemplateParameter that exposes this ParameterableElement as a formal
        ///     parameter.
        /// </summary>
        TemplateParameter templateParameter { get; set; }

        /// <summary>
        /// The query isCompatibleWith() determines if this ParameterableElement is
        /// compatible with the specified ParameterableElement. By default, this
        /// ParameterableElement is compatible with another ParameterableElement p if the
        /// kind of this ParameterableElement is the same as or a subtype of the kind of p.
        /// Subclasses of ParameterableElement should override this operation to specify
        /// different compatibility constraints.
        /// </summary>
        /// <param name="result"></param>
        /// <param name="p"></param>
        //void isCompatibleWith(result, ParameterableElement p){

        //}

        /// <summary>
        /// The query isTemplateParameter() determines if this ParameterableElement is
        /// exposed as a formal TemplateParameter.
        /// </summary>
        /// <param name="result"></param>
        //void isTemplateParameter(result){

        //}
    }
} //end namespace CommonStructure