///////////////////////////////////////////////////////////
//  Realization.cs
//  Implementation of the Class Realization
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:12
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.CommonStructure
{
    /// <summary>
    ///     Realization is a specialized Abstraction relationship between two sets of model
    ///     Elements, one representing a specification (the supplier) and the other
    ///     represents an implementation of the latter (the client). Realization can be
    ///     used to model stepwise refinement, optimizations, transformations, templates,
    ///     model synthesis, framework composition, etc.
    /// </summary>
    public interface Realization : Abstraction
    {
    }
} //end namespace CommonStructure