///////////////////////////////////////////////////////////
//  Relationship.cs
//  Implementation of the Class Relationship
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:13
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.CommonStructure
{
    /// <summary>
    ///     Relationship is an concept that specifies some kind of relationship
    ///     between Elements.
    /// </summary>
    public interface Relationship : Element
    {
        /// <summary>
        ///     Specifies the elements related by the Relationship.
        /// </summary>
        Element relatedElement { get; set; }
    }
} //end namespace CommonStructure