///////////////////////////////////////////////////////////
//  TemplateParameter.cs
//  Implementation of the Class TemplateParameter
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:15
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.CommonStructure
{
    /// <summary>
    ///     A TemplateParameter exposes a ParameterableElement as a formal parameter of a
    ///     template.
    /// </summary>
    public interface TemplateParameter : Element
    {
        /// <summary>
        ///     The ParameterableElement exposed by this TemplateParameter.
        /// </summary>
        ParameterableElement parameteredElement { get; set; }

        /// <summary>
        ///     The ParameterableElement that is the default for this formal TemplateParameter.
        /// </summary>
        ParameterableElement Default { get; set; }

        /// <summary>
        ///     The ParameterableElement that is owned by this TemplateParameter for the
        ///     purpose of exposing it as the parameteredElement.
        /// </summary>
        ParameterableElement ownedParameteredElement { get; set; }

        /// <summary>
        ///     The ParameterableElement that is owned by this TemplateParameter for the
        ///     purpose of providing a default.
        /// </summary>
        ParameterableElement ownedDefault { get; set; }
    }
} //end namespace CommonStructure