///////////////////////////////////////////////////////////
//  TemplateSignature.cs
//  Implementation of the Class TemplateSignature
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:15
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;

namespace UML.CommonStructure
{
    /// <summary>
    ///     A Template Signature bundles the set of formal TemplateParameters for a
    ///     template.
    /// </summary>
    public interface TemplateSignature : Element
    {
        /// <summary>
        ///     The ordered set of all formal TemplateParameters for this TemplateSignature.
        /// </summary>
        TemplateParameter parameter { get; set; }

        /// <summary>
        ///     The formal parameters that are owned by this TemplateSignature.
        /// </summary>
        IEnumerable<TemplateParameter> ownedParameter { get; set; }
    }
} //end namespace CommonStructure