///////////////////////////////////////////////////////////
//  Type.cs
//  Implementation of the Class Type
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:16
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.CommonStructure
{
    /// <summary>
    ///     A Type constrains the values represented by a TypedElement.
    /// </summary>
    public interface Type : PackageableElement
    {
        /// <summary>
        /// The query conformsTo() gives true for a Type that conforms to another. By
        /// default, two Types do not conform to each other. This query is intended to be
        /// redefined for specific conformance situations.
        /// </summary>
        /// <param name="result"></param>
        /// <param name="other"></param>
        //void conformsTo(result, Type other){

        //}
    }
} //end namespace CommonStructure