///////////////////////////////////////////////////////////
//  Usage.cs
//  Implementation of the Class Usage
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:17
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.CommonStructure
{
    /// <summary>
    ///     A Usage is a Dependency in which the client Element requires the supplier
    ///     Element (or set of Elements) for its full implementation or operation.
    /// </summary>
    public interface Usage : Dependency
    {
    }
} //end namespace CommonStructure