///////////////////////////////////////////////////////////
//  DurationObservation.cs
//  Implementation of the Class DurationObservation
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:59
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.CommonStructure;

namespace UML.Values
{
    /// <summary>
    ///     A DurationObservation is a reference to a duration during an execution. It
    ///     points out the NamedElement(s) in the model to observe and whether the
    ///     observations are when this NamedElement is entered or when it is exited.
    /// </summary>
    public interface DurationObservation : Observation
    {
        /// <summary>
        ///     The value of firstEvent[i] is related to event[i] (where i is 1 or 2). If
        ///     firstEvent[i] is true, then the corresponding observation event is the first
        ///     time instant the execution enters event[i]. If firstEvent[i] is false, then the
        ///     corresponding observation event is the time instant the execution exits
        ///     event[i].
        /// </summary>
        bool firstEvent { get; set; }

        /// <summary>
        ///     The DurationObservation is determined as the duration between the entering or
        ///     exiting of a single event Element during execution, or the entering/exiting of
        ///     one event Element and the entering/exiting of a second.
        /// </summary>
        NamedElement Event { get; set; }
    }
} //end namespace Values