///////////////////////////////////////////////////////////
//  DurationInterval.cs
//  Implementation of the Class DurationInterval
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:59
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Values
{
    /// <summary>
    ///     A DurationInterval defines the range between two Durations.
    /// </summary>
    public interface DurationInterval : Interval
    {
        /// <summary>
        ///     Refers to the Duration denoting the minimum value of the range.
        /// </summary>
        Duration min { get; set; }

        /// <summary>
        ///     Refers to the Duration denoting the maximum value of the range.
        /// </summary>
        Duration max { get; set; }
    }
} //end namespace Values