///////////////////////////////////////////////////////////
//  Interval.cs
//  Implementation of the Class Interval
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:04
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Values
{
    /// <summary>
    ///     An Interval defines the range between two ValueSpecifications.
    /// </summary>
    public interface Interval : ValueSpecification
    {
        /// <summary>
        ///     Refers to the ValueSpecification denoting the minimum value of the range.
        /// </summary>
        ValueSpecification min { get; set; }

        /// <summary>
        ///     Refers to the ValueSpecification denoting the maximum value of the range.
        /// </summary>
        ValueSpecification max { get; set; }
    }
} //end namespace Values