///////////////////////////////////////////////////////////
//  LiteralInteger.cs
//  Implementation of the Class LiteralInteger
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:05
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Values
{
    /// <summary>
    ///     A LiteralInteger is a specification of an Integer value.
    /// </summary>
    public interface LiteralInteger : LiteralSpecification
    {
        /// <summary>
        ///     The specified Integer value.
        /// </summary>
        string value { get; set; }


        /// <summary>
        /// The query integerValue() gives the value.
        /// </summary>
        /// <param name="result"></param>
        //void integerValue(result){

        //}

        /// <summary>
        /// The query isComputable() is redefined to be true.
        /// </summary>
        /// <param name="result"></param>
        //void isComputable(result){

        //}
    }
} //end namespace Values