///////////////////////////////////////////////////////////
//  LiteralReal.cs
//  Implementation of the Class LiteralReal
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:05
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Values
{
    /// <summary>
    ///     A LiteralReal is a specification of a Real value.
    /// </summary>
    public interface LiteralReal : LiteralSpecification
    {
        /// <summary>
        ///     The specified Real value.
        /// </summary>
        string value { get; set; }


        /// <summary>
        /// The query isComputable() is redefined to be true.
        /// </summary>
        /// <param name="result"></param>
        //void isComputable(result){

        //}

        /// <summary>
        /// The query realValue() gives the value.
        /// </summary>
        /// <param name="result"></param>
        //void realValue(result){

        //}
    }
} //end namespace Values