///////////////////////////////////////////////////////////
//  LiteralUnlimitedNatural.cs
//  Implementation of the Class LiteralUnlimitedNatural
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:06
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Values
{
    /// <summary>
    ///     A LiteralUnlimitedNatural is a specification of an UnlimitedNatural number.
    /// </summary>
    public interface LiteralUnlimitedNatural : LiteralSpecification
    {
        /// <summary>
        ///     The specified UnlimitedNatural value.
        /// </summary>
        string value { get; set; }


        /// <summary>
        /// The query isComputable() is redefined to be true.
        /// </summary>
        /// <param name="result"></param>
        //void isComputable(result){

        //}

        /// <summary>
        /// The query unlimitedValue() gives the value.
        /// </summary>
        /// <param name="result"></param>
        //void unlimitedValue(result){

        //}
    }
} //end namespace Values