///////////////////////////////////////////////////////////
//  LiteralSpecification.cs
//  Implementation of the Class LiteralSpecification
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:05
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Values
{
    /// <summary>
    ///     A LiteralSpecification identifies a literal constant being modeled.
    /// </summary>
    public interface LiteralSpecification : ValueSpecification
    {
    }
} //end namespace Values