///////////////////////////////////////////////////////////
//  LiteralNull.cs
//  Implementation of the Class LiteralNull
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:05
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Values
{
    /// <summary>
    ///     A LiteralNull specifies the lack of a value.
    /// </summary>
    public interface LiteralNull : LiteralSpecification
    {
        /// <summary>
        /// The query isComputable() is redefined to be true.
        /// </summary>
        /// <param name="result"></param>
        //void isComputable(result){

        //}

        /// <summary>
        /// The query isNull() returns true.
        /// </summary>
        /// <param name="result"></param>
        //void isNull(result){

        //}
    }
} //end namespace Values