///////////////////////////////////////////////////////////
//  LiteralBoolean.cs
//  Implementation of the Class LiteralBoolean
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:05
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Values
{
    /// <summary>
    ///     A LiteralBoolean is a specification of a Boolean value.
    /// </summary>
    public interface LiteralBoolean : LiteralSpecification
    {
        /// <summary>
        ///     The specified Boolean value.
        /// </summary>
        string value { get; set; }


        /// <summary>
        /// The query booleanValue() gives the value.
        /// </summary>
        /// <param name="result"></param>
        //void booleanValue(result){

        //}

        /// <summary>
        /// The query isComputable() is redefined to be true.
        /// </summary>
        /// <param name="result"></param>
        //void isComputable(result){

        //}
    }
} //end namespace Values