///////////////////////////////////////////////////////////
//  Observation.cs
//  Implementation of the Class Observation
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:07
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.CommonStructure;

namespace UML.Values
{
    /// <summary>
    ///     Observation specifies a value determined by observing an event or events that
    ///     occur relative to other model Elements.
    /// </summary>
    public interface Observation : PackageableElement
    {
    }
} //end namespace Values