///////////////////////////////////////////////////////////
//  TimeExpression.cs
//  Implementation of the Class TimeExpression
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:16
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;

namespace UML.Values
{
    /// <summary>
    ///     A TimeExpression is a ValueSpecification that represents a time value.
    /// </summary>
    public interface TimeExpression : ValueSpecification
    {
        /// <summary>
        ///     Refers to the Observations that are involved in the computation of the
        ///     TimeExpression value.
        /// </summary>
        IEnumerable<Observation> observation { get; set; }

        /// <summary>
        ///     A ValueSpecification that evaluates to the value of the TimeExpression.
        /// </summary>
        ValueSpecification expr { get; set; }
    }
} //end namespace Values