///////////////////////////////////////////////////////////
//  TimeConstraint.cs
//  Implementation of the Class TimeConstraint
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:16
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Values
{
    /// <summary>
    ///     A TimeConstraint is a Constraint that refers to a TimeInterval.
    /// </summary>
    public interface TimeConstraint : IntervalConstraint
    {
        /// <summary>
        ///     The value of firstEvent is related to the constrainedElement. If firstEvent is
        ///     true, then the corresponding observation event is the first time instant the
        ///     execution enters the constrainedElement. If firstEvent is false, then the
        ///     corresponding observation event is the last time instant the execution is
        ///     within the constrainedElement.
        /// </summary>
        bool firstEvent { get; set; }

        /// <summary>
        ///     TheTimeInterval constraining the duration.
        /// </summary>
        TimeInterval specification { get; set; }
    }
} //end namespace Values