///////////////////////////////////////////////////////////
//  TimeInterval.cs
//  Implementation of the Class TimeInterval
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:16
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Values
{
    /// <summary>
    ///     A TimeInterval defines the range between two TimeExpressions.
    /// </summary>
    public interface TimeInterval : Interval
    {
        /// <summary>
        ///     Refers to the TimeExpression denoting the minimum value of the range.
        /// </summary>
        TimeExpression min { get; set; }

        /// <summary>
        ///     Refers to the TimeExpression denoting the maximum value of the range.
        /// </summary>
        TimeExpression max { get; set; }
    }
} //end namespace Values