///////////////////////////////////////////////////////////
//  Actor.cs
//  Implementation of the Class Actor
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:52
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.SimpleClassifiers;

namespace UML.UseCases
{
    /// <summary>
    ///     An Actor specifies a role played by a user or any other system that interacts
    ///     with the subject.
    /// </summary>
    public interface Actor : BehavioredClassifier
    {
    }
} //end namespace UseCases