///////////////////////////////////////////////////////////
//  ExtensionPoint.cs
//  Implementation of the Class ExtensionPoint
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:01
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.Classification;

namespace UML.UseCases
{
    /// <summary>
    ///     An ExtensionPoint identifies a point in the behavior of a UseCase where that
    ///     behavior can be extended by the behavior of some other (extending) UseCase, as
    ///     specified by an Extend relationship.
    /// </summary>
    public interface ExtensionPoint : RedefinableElement
    {
    }
} //end namespace UseCases