///////////////////////////////////////////////////////////
//  Include.cs
//  Implementation of the Class Include
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:02
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.CommonStructure;

namespace UML.UseCases
{
    /// <summary>
    ///     An Include relationship specifies that a UseCase contains the behavior defined
    ///     in another UseCase.
    /// </summary>
    public interface Include : NamedElement, DirectedRelationship
    {
        /// <summary>
        ///     The UseCase that is to be included.
        /// </summary>
        UseCase addition { get; set; }
    }
} //end namespace UseCases