///////////////////////////////////////////////////////////
//  CommunicationPath.cs
//  Implementation of the Class CommunicationPath
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:56
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.StructuredClassifiers;

namespace UML.Deployments
{
    /// <summary>
    ///     A communication path is an association between two deployment targets, through
    ///     which they are able to exchange signals and messages.
    /// </summary>
    public interface CommunicationPath : Association
    {
    }
} //end namespace Deployments