///////////////////////////////////////////////////////////
//  Deployment.cs
//  Implementation of the Class Deployment
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:58
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using UML.CommonStructure;

namespace UML.Deployments
{
    /// <summary>
    ///     A deployment is the allocation of an artifact or artifact instance to a
    ///     deployment target.
    ///     A component deployment is the deployment of one or more artifacts or artifact
    ///     instances to a deployment target, optionally parameterized by a deployment
    ///     specification. Examples are executables and configuration files.
    /// </summary>
    public interface Deployment : Dependency
    {
        /// <summary>
        ///     The specification of properties that parameterize the deployment and execution
        ///     of one or more Artifacts.
        /// </summary>
        IEnumerable<DeploymentSpecification> configuration { get; set; }

        /// <summary>
        ///     The Artifacts that are deployed onto a Node. This association specializes the
        ///     supplier association.
        /// </summary>
        IEnumerable<DeployedArtifact> deployedArtifact { get; set; }
    }
} //end namespace Deployments