///////////////////////////////////////////////////////////
//  DeploymentTarget.cs
//  Implementation of the Class DeploymentTarget
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:58
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using UML.CommonStructure;

namespace UML.Deployments
{
    /// <summary>
    ///     A deployment target is the location for a deployed artifact.
    /// </summary>
    public interface DeploymentTarget : NamedElement
    {
        /// <summary>
        ///     The set of Deployments for a DeploymentTarget.
        /// </summary>
        IEnumerable<Deployment> deployment { get; set; }

        /// <summary>
        ///     The set of elements that are manifested in an Artifact that is involved in
        ///     Deployment to a DeploymentTarget.
        /// </summary>
        IEnumerable<PackageableElement> deployedElement { get; set; }

        /// <summary>
        /// Derivation for DeploymentTarget::/deployedElement
        /// </summary>
        /// <param name="result"></param>
        //UML.CommonStructure.PackageableElement deployedElement(PackageableElement result){

        //	return null;
        //}
    }
} //end namespace Deployments