///////////////////////////////////////////////////////////
//  DeployedArtifact.cs
//  Implementation of the Class DeployedArtifact
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:58
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.CommonStructure;

namespace UML.Deployments
{
    /// <summary>
    ///     A deployed artifact is an artifact or artifact instance that has been deployed
    ///     to a deployment target.
    /// </summary>
    public interface DeployedArtifact : NamedElement
    {
    }
} //end namespace Deployments