///////////////////////////////////////////////////////////
//  Device.cs
//  Implementation of the Class Device
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:58
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Deployments
{
    /// <summary>
    ///     A device is a physical computational resource with processing capability upon
    ///     which artifacts may be deployed for execution. Devices may be complex (i.e.,
    ///     they may consist of other devices).
    /// </summary>
    public interface Device : Node
    {
    }
} //end namespace Deployments