///////////////////////////////////////////////////////////
//  ExecutionEnvironment.cs
//  Implementation of the Class ExecutionEnvironment
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:00
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Deployments
{
    /// <summary>
    ///     An execution environment is a node that offers an execution environment for
    ///     specific types of components that are deployed on it in the form of executable
    ///     artifacts.
    /// </summary>
    public interface ExecutionEnvironment : Node
    {
    }
} //end namespace Deployments