///////////////////////////////////////////////////////////
//  Manifestation.cs
//  Implementation of the Class Manifestation
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:06
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.CommonStructure;

namespace UML.Deployments
{
    /// <summary>
    ///     A manifestation is the concrete physical rendering of one or more model
    ///     elements by an artifact.
    /// </summary>
    public interface Manifestation : Abstraction
    {
        /// <summary>
        ///     The model element that is utilized in the manifestation in an Artifact.
        /// </summary>
        PackageableElement utilizedElement { get; set; }
    }
} //end namespace Deployments