///////////////////////////////////////////////////////////
//  Node.cs
//  Implementation of the Class Node
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:07
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using UML.StructuredClassifiers;

namespace UML.Deployments
{
    /// <summary>
    ///     A Node is computational resource upon which artifacts may be deployed for
    ///     execution. Nodes can be interconnected through communication paths to define
    ///     network structures.
    /// </summary>
    public interface Node : DeploymentTarget, Class
    {
        /// <summary>
        ///     The Nodes that are defined (nested) within the Node.
        /// </summary>
        IEnumerable<Node> nestedNode { get; set; }
    }
} //end namespace Deployments