///////////////////////////////////////////////////////////
//  InformationFlow.cs
//  Implementation of the Class InformationFlow
//  Generated by Enterprise Architect
//  Created on:      31-ÿíâ-2019 22:00:02
//  Original author: Àíäðåé
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using UML.Activities;
using UML.Classification;
using UML.CommonStructure;
using UML.Interactions;
using UML.StructuredClassifiers;

namespace UML.InformationFlows
{
    /// <summary>
    ///     InformationFlows describe circulation of information through a system in a
    ///     general manner. They do not specify the nature of the information, mechanisms
    ///     by which it is conveyed, sequences of exchange or any control conditions.
    ///     During more detailed modeling, representation and realization links may be
    ///     added to specify which model elements implement an InformationFlow and to show
    ///     how information is conveyed.  InformationFlows require some kind of
    ///     “information channel” for unidirectional transmission of information items from
    ///     sources to targets.  They specify the information channel’s realizations, if
    ///     any, and identify the information that flows along them.  Information moving
    ///     along the information channel may be represented by InformationItems
    ///     and by concrete Classifiers.
    /// </summary>
    public interface InformationFlow : PackageableElement, DirectedRelationship
    {
        /// <summary>
        ///     Defines to which target the conveyed InformationItems are directed.
        /// </summary>
        NamedElement informationTarget { get; set; }

        /// <summary>
        ///     Determines which Connectors will realize the specified flow.
        /// </summary>
        IEnumerable<Connector> realizingConnector { get; set; }

        /// <summary>
        ///     Determines which Relationship will realize the specified flow.
        /// </summary>
        IEnumerable<Relationship> realization { get; set; }

        /// <summary>
        ///     Defines from which source the conveyed InformationItems are initiated.
        /// </summary>
        NamedElement informationSource { get; set; }

        /// <summary>
        ///     Determines which Messages will realize the specified flow.
        /// </summary>
        IEnumerable<Message> realizingMessage { get; set; }

        /// <summary>
        ///     Determines which ActivityEdges will realize the specified flow.
        /// </summary>
        IEnumerable<ActivityEdge> realizingActivityEdge { get; set; }

        /// <summary>
        ///     Specifies the information items that may circulate on this information flow.
        /// </summary>
        Classifier conveyed { get; set; }
    }
} //end namespace InformationFlows