///////////////////////////////////////////////////////////
//  InstanceValue.cs
//  Implementation of the Class InstanceValue
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:03
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.Values;

namespace UML.Classification
{
    /// <summary>
    ///     An InstanceValue is a ValueSpecification that identifies an instance.
    /// </summary>
    public interface InstanceValue : ValueSpecification
    {
        /// <summary>
        ///     The InstanceSpecification that represents the specified value.
        /// </summary>
        InstanceSpecification instance { get; set; }
    }
} //end namespace Classification