///////////////////////////////////////////////////////////
//  OperationTemplateParameter.cs
//  Implementation of the Class OperationTemplateParameter
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:08
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.CommonStructure;

namespace UML.Classification
{
    /// <summary>
    ///     An OperationTemplateParameter exposes an Operation as a formal parameter for a
    ///     template.
    /// </summary>
    public interface OperationTemplateParameter : TemplateParameter
    {
        /// <summary>
        ///     The Operation exposed by this OperationTemplateParameter.
        /// </summary>
        Operation parameteredElement { get; set; }
    }
} //end namespace Classification