///////////////////////////////////////////////////////////
//  ParameterEffectKind.cs
//  Implementation of the Enumeration ParameterEffectKind
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:09
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Classification
{
    /// <summary>
    ///     ParameterEffectKind is an Enumeration that indicates the effect of a Behavior
    ///     on values passed in or out of its parameters.
    /// </summary>
    public enum ParameterEffectKind
    {
        /// <summary>
        ///     Indicates that the behavior creates values.
        /// </summary>
        create,

        /// <summary>
        ///     Indicates objects that are values of the parameter have values of their
        ///     properties, or links in which they participate, or their classifiers retrieved
        ///     during executions of the behavior.
        /// </summary>
        read,

        /// <summary>
        ///     Indicates objects that are values of the parameter have values of their
        ///     properties, or links in which they participate, or their classification changed
        ///     during executions of the behavior.
        /// </summary>
        update,

        /// <summary>
        ///     Indicates objects that are values of the parameter do not exist after
        ///     executions of the behavior are finished.
        /// </summary>
        delete
    } //end ParameterEffectKind
} //end namespace Classification