///////////////////////////////////////////////////////////
//  ParameterSet.cs
//  Implementation of the Class ParameterSet
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:09
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using UML.CommonStructure;

namespace UML.Classification
{
    /// <summary>
    ///     A ParameterSet designates alternative sets of inputs or outputs that a Behavior
    ///     may use.
    /// </summary>
    public interface ParameterSet : NamedElement
    {
        /// <summary>
        ///     Parameters in the ParameterSet.
        /// </summary>
        Parameter parameter { get; set; }

        /// <summary>
        ///     A constraint that should be satisfied for the owner of the Parameters in an
        ///     input ParameterSet to start execution using the values provided for those
        ///     Parameters, or the owner of the Parameters in an output ParameterSet to end
        ///     execution providing the values for those Parameters, if all preconditions and
        ///     conditions on input ParameterSets were satisfied.
        /// </summary>
        IEnumerable<Constraint> condition { get; set; }
    }
} //end namespace Classification