///////////////////////////////////////////////////////////
//  Slot.cs
//  Implementation of the Class Slot
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:13
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using UML.CommonStructure;
using UML.Values;

namespace UML.Classification
{
    /// <summary>
    ///     A Slot designates that an entity modeled by an InstanceSpecification has a
    ///     value or values for a specific StructuralFeature.
    /// </summary>
    public interface Slot : Element
    {
        /// <summary>
        ///     The value or values held by the Slot.
        /// </summary>
        IEnumerable<ValueSpecification> value { get; set; }

        /// <summary>
        ///     The StructuralFeature that specifies the values that may be held by the Slot.
        /// </summary>
        StructuralFeature definingFeature { get; set; }
    }
} //end namespace Classification