///////////////////////////////////////////////////////////
//  AssociationClass.cs
//  Implementation of the Class AssociationClass
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:53
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.StructuredClassifiers
{
    /// <summary>
    ///     A model element that has both Association and Class properties. An
    ///     AssociationClass can be seen as an Association that also has Class properties,
    ///     or as a Class that also has Association properties. It not only connects a set
    ///     of Classifiers but also defines a set of Features that belong to the
    ///     Association itself and not to any of the associated Classifiers.
    /// </summary>
    public interface AssociationClass : Association, Class
    {
    }
} //end namespace StructuredClassifiers