///////////////////////////////////////////////////////////
//  Association.cs
//  Implementation of the Class Association
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:53
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using UML.Classification;
using UML.CommonStructure;

namespace UML.StructuredClassifiers
{
    /// <summary>
    ///     A link is a tuple of values that refer to typed objects.  An Association
    ///     classifies a set of links, each of which is an instance of the Association.
    ///     Each value in the link refers to an instance of the type of the corresponding
    ///     end of the Association.
    /// </summary>
    public interface Association : Classifier, Relationship
    {
        /// <summary>
        ///     Specifies whether the Association is derived from other model elements such as
        ///     other Associations.
        /// </summary>
        bool isDerived { get; set; }

        /// <summary>
        ///     The navigable ends that are owned by the Association itself.
        /// </summary>
        IEnumerable<Property> navigableOwnedEnd { get; set; }

        /// <summary>
        ///     The ends that are owned by the Association itself.
        /// </summary>
        IEnumerable<Property> ownedEnd { get; set; }

        /// <summary>
        ///     The Classifiers that are used as types of the ends of the Association.
        /// </summary>
        Type endType { get; set; }

        /// <summary>
        ///     Each end represents participation of instances of the Classifier connected to
        ///     the end in links of the Association.
        /// </summary>
        IEnumerable<Property> memberEnd { get; set; }

        /// <summary>
        /// endType is derived from the types of the member ends.
        /// </summary>
        /// <param name="result"></param>
        //UML.CommonStructure.Type endType(Type result){

        //	return null;
        //}
    }
} //end namespace StructuredClassifiers