///////////////////////////////////////////////////////////
//  Collaboration.cs
//  Implementation of the Class Collaboration
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:55
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using UML.SimpleClassifiers;

namespace UML.StructuredClassifiers
{
    /// <summary>
    ///     A Collaboration describes a structure of collaborating elements (roles), each
    ///     performing a specialized function, which collectively accomplish some desired
    ///     functionality.
    /// </summary>
    public interface Collaboration : BehavioredClassifier, StructuredClassifier
    {
        /// <summary>
        ///     Represents the participants in the Collaboration.
        /// </summary>
        IEnumerable<ConnectableElement> collaborationRole { get; set; }
    }
} //end namespace StructuredClassifiers