///////////////////////////////////////////////////////////
//  ComponentRealization.cs
//  Implementation of the Class ComponentRealization
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:56
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.Classification;
using UML.CommonStructure;

namespace UML.StructuredClassifiers
{
    /// <summary>
    ///     Realization is specialized to (optionally) define the Classifiers that realize
    ///     the contract offered by a Component in terms of its provided and required
    ///     Interfaces. The Component forms an abstraction from these various Classifiers.
    /// </summary>
    public interface ComponentRealization : Realization
    {
        /// <summary>
        ///     The Classifiers that are involved in the implementation of the Component that
        ///     owns this Realization.
        /// </summary>
        Classifier realizingClassifier { get; set; }
    }
} //end namespace StructuredClassifiers