///////////////////////////////////////////////////////////
//  ConnectableElementTemplateParameter.cs
//  Implementation of the Class ConnectableElementTemplateParameter
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:56
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.CommonStructure;

namespace UML.StructuredClassifiers
{
    /// <summary>
    ///     A ConnectableElementTemplateParameter exposes a ConnectableElement as a formal
    ///     parameter for a template.
    /// </summary>
    public interface ConnectableElementTemplateParameter : TemplateParameter
    {
        /// <summary>
        ///     The ConnectableElement for this ConnectableElementTemplateParameter.
        /// </summary>
        ConnectableElement parameteredElement { get; set; }
    }
} //end namespace StructuredClassifiers