///////////////////////////////////////////////////////////
//  ConnectorKind.cs
//  Implementation of the Enumeration ConnectorKind
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:57
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.StructuredClassifiers
{
    /// <summary>
    ///     ConnectorKind is an enumeration that defines whether a Connector is an assembly
    ///     or a delegation.
    /// </summary>
    public enum ConnectorKind
    {
        /// <summary>
        ///     Indicates that the Connector is an assembly Connector.
        /// </summary>
        assembly,

        /// <summary>
        ///     Indicates that the Connector is a delegation Connector.
        /// </summary>
        delegation
    } //end ConnectorKind
} //end namespace StructuredClassifiers