///////////////////////////////////////////////////////////
//  BehavioredClassifier.cs
//  Implementation of the Class BehavioredClassifier
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:54
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using UML.Classification;
using UML.CommonBehavior;

namespace UML.SimpleClassifiers
{
    /// <summary>
    ///     A BehavioredClassifier may have InterfaceRealizations, and owns a set of
    ///     Behaviors one of which may specify the behavior of the BehavioredClassifier
    ///     itself.
    /// </summary>
    public interface BehavioredClassifier : Classifier
    {
        /// <summary>
        ///     The set of InterfaceRealizations owned by the BehavioredClassifier. Interface
        ///     realizations reference the Interfaces of which the BehavioredClassifier is an
        ///     implementation.
        /// </summary>
        IEnumerable<InterfaceRealization> interfaceRealization { get; set; }

        /// <summary>
        ///     A Behavior that specifies the behavior of the BehavioredClassifier itself.
        /// </summary>
        Behavior classifierBehavior { get; set; }

        /// <summary>
        ///     Behaviors owned by a BehavioredClassifier.
        /// </summary>
        IEnumerable<Behavior> ownedBehavior { get; set; }
    }
} //end namespace SimpleClassifiers