///////////////////////////////////////////////////////////
//  DataType.cs
//  Implementation of the Class DataType
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:57
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using UML.Classification;

namespace UML.SimpleClassifiers
{
    /// <summary>
    ///     A DataType is a type whose instances are identified only by their value.
    /// </summary>
    public interface DataType : Classifier
    {
        /// <summary>
        ///     The Operations owned by the DataType.
        /// </summary>
        IEnumerable<Operation> ownedOperation { get; set; }

        /// <summary>
        ///     The attributes owned by the DataType.
        /// </summary>
        IEnumerable<Property> ownedAttribute { get; set; }
    }
} //end namespace SimpleClassifiers