///////////////////////////////////////////////////////////
//  InterfaceRealization.cs
//  Implementation of the Class InterfaceRealization
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:04
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.CommonStructure;

namespace UML.SimpleClassifiers
{
    /// <summary>
    ///     An InterfaceRealization is a specialized realization relationship between a
    ///     BehavioredClassifier and an Interface. This relationship signifies that the
    ///     realizing BehavioredClassifier conforms to the contract specified by the
    ///     Interface.
    /// </summary>
    public interface InterfaceRealization : Realization
    {
        /// <summary>
        ///     References the public interface specifying the conformance contract.
        /// </summary>
        Interface contract { get; set; }
    }
} //end namespace SimpleClassifiers