///////////////////////////////////////////////////////////
//  Interface.cs
//  Implementation of the Class Interface
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:04
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using UML.Classification;
using UML.StateMachines;

namespace UML.SimpleClassifiers
{
    /// <summary>
    ///     Interfaces declare coherent services that are implemented by
    ///     BehavioredClassifiers that implement the Interfaces via InterfaceRealizations.
    /// </summary>
    public interface Interface : Classifier
    {
        /// <summary>
        ///     The attributes (i.e., the Properties) owned by the Interface.
        /// </summary>
        IEnumerable<Property> ownedAttribute { get; set; }

        /// <summary>
        ///     The Operations owned by the Interface.
        /// </summary>
        IEnumerable<Operation> ownedOperation { get; set; }

        /// <summary>
        ///     References all the Classifiers that are defined (nested) within the Interface.
        /// </summary>
        IEnumerable<Classifier> nestedClassifier { get; set; }

        /// <summary>
        ///     References all the Interfaces redefined by this Interface.
        /// </summary>
        IEnumerable<Interface> redefinedInterface { get; set; }

        /// <summary>
        ///     Receptions that objects providing this public interface are willing to accept.
        /// </summary>
        IEnumerable<Reception> ownedReception { get; set; }

        /// <summary>
        ///     References a ProtocolStateMachine specifying the legal sequences of the
        ///     invocation of the BehavioralFeatures described in the Interface.
        /// </summary>
        ProtocolStateMachine protocol { get; set; }
    }
} //end namespace SimpleClassifiers