///////////////////////////////////////////////////////////
//  PrimitiveType.cs
//  Implementation of the Class PrimitiveType
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:10
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.SimpleClassifiers
{
    /// <summary>
    ///     A PrimitiveType defines a predefined DataType, without any substructure. A
    ///     PrimitiveType may have an algebra and operations defined outside of UML, for
    ///     example, mathematically.
    /// </summary>
    public interface PrimitiveType : DataType
    {
    }
} //end namespace SimpleClassifiers