///////////////////////////////////////////////////////////
//  Reception.cs
//  Implementation of the Class Reception
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:12
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.Classification;

namespace UML.SimpleClassifiers
{
    /// <summary>
    ///     A Reception is a declaration stating that a Classifier is prepared to react to
    ///     the receipt of a Signal.
    /// </summary>
    public interface Reception : BehavioralFeature
    {
        /// <summary>
        ///     The Signal that this Reception handles.
        /// </summary>
        Signal signal { get; set; }
    }
} //end namespace SimpleClassifiers