///////////////////////////////////////////////////////////
//  Signal.cs
//  Implementation of the Class Signal
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:13
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using UML.Classification;

namespace UML.SimpleClassifiers
{
    /// <summary>
    ///     A Signal is a specification of a kind of communication between objects in which
    ///     a reaction is asynchronously triggered in the receiver without a reply.
    /// </summary>
    public interface Signal : Classifier
    {
        /// <summary>
        ///     The attributes owned by the Signal.
        /// </summary>
        IEnumerable<Property> ownedAttribute { get; set; }
    }
} //end namespace SimpleClassifiers