///////////////////////////////////////////////////////////
//  FinalState.cs
//  Implementation of the Class FinalState
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:01
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.StateMachines
{
    /// <summary>
    ///     A special kind of State, which, when entered, signifies that the enclosing
    ///     Region has completed. If the enclosing Region is directly contained in a
    ///     StateMachine and all other Regions in that StateMachine also are completed,
    ///     then it means that the entire StateMachine behavior is completed.
    /// </summary>
    public interface FinalState : State
    {
        /// <summary>
        /// The query isConsistentWith() specifies a FinalState can only be redefined by a
        /// FinalState.
        /// </summary>
        /// <param name="redefiningElement"></param>
        /// <param name="result"></param>
        //void isConsistentWith(RedefinableElement redefiningElement, result){

        //}
    }
} //end namespace StateMachines