///////////////////////////////////////////////////////////
//  AnyReceiveEvent.cs
//  Implementation of the Class AnyReceiveEvent
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:53
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.CommonBehavior
{
    /// <summary>
    ///     A trigger for an AnyReceiveEvent is triggered by the receipt of any message
    ///     that is not explicitly handled by any related trigger.
    /// </summary>
    public interface AnyReceiveEvent : MessageEvent
    {
    }
} //end namespace CommonBehavior