///////////////////////////////////////////////////////////
//  CallEvent.cs
//  Implementation of the Class CallEvent
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:54
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.Classification;

namespace UML.CommonBehavior
{
    /// <summary>
    ///     A CallEvent models the receipt by an object of a message invoking a call of an
    ///     Operation.
    /// </summary>
    public interface CallEvent : MessageEvent
    {
        /// <summary>
        ///     Designates the Operation whose invocation raised the CalEvent.
        /// </summary>
        Operation operation { get; set; }
    }
} //end namespace CommonBehavior