///////////////////////////////////////////////////////////
//  Event.cs
//  Implementation of the Class Event
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:00
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.CommonStructure;

namespace UML.CommonBehavior
{
    /// <summary>
    ///     An Event is the specification of some occurrence that may potentially trigger
    ///     effects by an object.
    /// </summary>
    public interface Event : PackageableElement
    {
    }
} //end namespace CommonBehavior