///////////////////////////////////////////////////////////
//  FunctionBehavior.cs
//  Implementation of the Class FunctionBehavior
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:02
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.SimpleClassifiers;

namespace UML.CommonBehavior
{
    /// <summary>
    ///     A FunctionBehavior is an OpaqueBehavior that does not access or modify any
    ///     objects or other external data.
    /// </summary>
    public interface FunctionBehavior : OpaqueBehavior
    {
        /// <summary>
        ///     The hasAllDataTypeAttributes query tests whether the types of the attributes of
        ///     the given DataType are all DataTypes, and similarly for all those DataTypes.
        /// </summary>
        /// <param name="result"></param>
        /// <param name="d"></param>
        bool hasAllDataTypeAttributes(DataType d);
    }
} //end namespace CommonBehavior