///////////////////////////////////////////////////////////
//  MessageEvent.cs
//  Implementation of the Class MessageEvent
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:06
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.CommonBehavior
{
    /// <summary>
    ///     A MessageEvent specifies the receipt by an object of either an Operation call
    ///     or a Signal instance.
    /// </summary>
    public interface MessageEvent : Event
    {
    }
} //end namespace CommonBehavior