///////////////////////////////////////////////////////////
//  OpaqueBehavior.cs
//  Implementation of the Class OpaqueBehavior
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:08
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.CommonBehavior
{
    /// <summary>
    ///     An OpaqueBehavior is a Behavior whose specification is given in a textual
    ///     language other than UML.
    /// </summary>
    public interface OpaqueBehavior : Behavior
    {
        /// <summary>
        ///     Specifies the behavior in one or more languages.
        /// </summary>
        string body { get; set; }

        /// <summary>
        ///     Languages the body strings use in the same order as the body strings.
        /// </summary>
        string language { get; set; }
    }
} //end namespace CommonBehavior