///////////////////////////////////////////////////////////
//  SignalEvent.cs
//  Implementation of the Class SignalEvent
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:13
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.SimpleClassifiers;

namespace UML.CommonBehavior
{
    /// <summary>
    ///     A SignalEvent represents the receipt of an asynchronous Signal instance.
    /// </summary>
    public interface SignalEvent : MessageEvent
    {
        /// <summary>
        ///     The specific Signal that is associated with this SignalEvent.
        /// </summary>
        Signal signal { get; set; }
    }
} //end namespace CommonBehavior