///////////////////////////////////////////////////////////
//  Trigger.cs
//  Implementation of the Class Trigger
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:16
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using UML.CommonStructure;
using UML.StructuredClassifiers;

namespace UML.CommonBehavior
{
    /// <summary>
    ///     A Trigger specifies a specific point  at which an Event occurrence may trigger
    ///     an effect in a Behavior. A Trigger may be qualified by the Port on which the
    ///     Event occurred.
    /// </summary>
    public interface Trigger : NamedElement
    {
        /// <summary>
        ///     A optional Port of through which the given effect is detected.
        /// </summary>
        IEnumerable<Port> port { get; set; }

        /// <summary>
        ///     The Event that detected by the Trigger.
        /// </summary>
        Event Event { get; set; }
    }
} //end namespace CommonBehavior