///////////////////////////////////////////////////////////
//  AcceptCallAction.cs
//  Implementation of the Class AcceptCallAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:51
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Actions
{
    /// <summary>
    ///     An AcceptCallAction is an AcceptEventAction that handles the receipt of a
    ///     synchronous call request. In addition to the values from the Operation input
    ///     parameters, the Action produces an output that is needed later to supply the
    ///     information to the ReplyAction necessary to return control to the caller. An
    ///     AcceptCallAction is for synchronous calls. If it is used to handle an
    ///     asynchronous call, execution of the subsequent ReplyAction will complete
    ///     immediately with no effect.
    /// </summary>
    public interface AcceptCallAction : AcceptEventAction
    {
        /// <summary>
        ///     An OutputPin where a value is placed containing sufficient information to
        ///     perform a subsequent ReplyAction and return control to the caller. The contents
        ///     of this value are opaque. It can be passed and copied but it cannot be
        ///     manipulated by the model.
        /// </summary>
        OutputPin returnInformation { get; set; }
    }
} //end namespace Actions