///////////////////////////////////////////////////////////
//  AcceptEventAction.cs
//  Implementation of the Class AcceptEventAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:51
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using UML.CommonBehavior;

namespace UML.Actions
{
    /// <summary>
    ///     An AcceptEventAction is an Action that waits for the occurrence of one or more
    ///     specific Events.
    /// </summary>
    public interface AcceptEventAction : Action
    {
        /// <summary>
        ///     Indicates whether there is a single OutputPin for a SignalEvent occurrence, or
        ///     multiple OutputPins for attribute values of the instance of the Signal
        ///     associated with a SignalEvent occurrence.
        /// </summary>
        bool isUnmarshall { get; set; }

        /// <summary>
        ///     OutputPins holding the values received from an Event occurrence.
        /// </summary>
        IEnumerable<OutputPin> result { get; set; }

        /// <summary>
        ///     The Triggers specifying the Events of which the AcceptEventAction waits for
        ///     occurrences.
        /// </summary>
        Trigger trigger { get; set; }
    }
} //end namespace Actions