///////////////////////////////////////////////////////////
//  AddStructuralFeatureValueAction.cs
//  Implementation of the Class AddStructuralFeatureValueAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:53
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Actions
{
    /// <summary>
    ///     An AddStructuralFeatureValueAction is a WriteStructuralFeatureAction for adding
    ///     values to a StructuralFeature.
    /// </summary>
    public interface AddStructuralFeatureValueAction : WriteStructuralFeatureAction
    {
        /// <summary>
        ///     Specifies whether existing values of the StructuralFeature should be removed
        ///     before adding the new value.
        /// </summary>
        bool isReplaceAll { get; set; }

        /// <summary>
        ///     The InputPin that gives the position at which to insert the value in an ordered
        ///     StructuralFeature. The type of the insertAt InputPin is UnlimitedNatural, but
        ///     the value cannot be zero. It is omitted for unordered StructuralFeatures.
        /// </summary>
        InputPin insertAt { get; set; }
    }
} //end namespace Actions