///////////////////////////////////////////////////////////
//  CallBehaviorAction.cs
//  Implementation of the Class CallBehaviorAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:54
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.Classification;
using UML.CommonBehavior;

namespace UML.Actions
{
    /// <summary>
    ///     A CallBehaviorAction is a CallAction that invokes a Behavior directly. The
    ///     argument values of the CallBehaviorAction are passed on the input Parameters of
    ///     the invoked Behavior. If the call is synchronous, the execution of the
    ///     CallBehaviorAction waits until the execution of the invoked Behavior completes
    ///     and the values of output Parameters of the Behavior are placed on the result
    ///     OutputPins. If the call is asynchronous, the CallBehaviorAction completes
    ///     immediately and no results values can be provided.
    /// </summary>
    public interface CallBehaviorAction : CallAction
    {
        /// <summary>
        ///     The Behavior being invoked.
        /// </summary>
        Behavior behavior { get; set; }

        /// <summary>
        ///     Return the in and inout ownedParameters of the Behavior being called.
        /// </summary>
        /// <param name="result"></param>
        Parameter inputParameters(Parameter result);

        /// <summary>
        ///     Return the inout, out and return ownedParameters of the Behavior being called.
        /// </summary>
        /// <param name="result"></param>
        Parameter outputParameters(Parameter result);
    }
} //end namespace Actions