///////////////////////////////////////////////////////////
//  Clause.cs
//  Implementation of the Class Clause
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:55
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using UML.Activities;
using UML.CommonStructure;

namespace UML.Actions
{
    /// <summary>
    ///     A Clause is an Element that represents a single branch of a ConditionalNode,
    ///     including a test and a body section. The body section is executed only if (but
    ///     not necessarily if) the test section evaluates to true.
    /// </summary>
    public interface Clause : Element
    {
        /// <summary>
        ///     A set of Clauses whose tests must all evaluate to false before this Clause can
        ///     evaluate its test.
        /// </summary>
        IEnumerable<Clause> predecessorClause { get; set; }

        /// <summary>
        ///     A set of Clauses that may not evaluate their tests unless the test for this
        ///     Clause evaluates to false.
        /// </summary>
        IEnumerable<Clause> successorClause { get; set; }

        /// <summary>
        ///     The set of ExecutableNodes that are executed if the test evaluates to true and
        ///     the Clause is chosen over other Clauses within the ConditionalNode that also
        ///     have tests that evaluate to true.
        /// </summary>
        IEnumerable<ExecutableNode> body { get; set; }

        /// <summary>
        ///     The set of ExecutableNodes that are executed in order to provide a test result
        ///     for the Clause.
        /// </summary>
        ExecutableNode test { get; set; }

        /// <summary>
        ///     The OutputPins on Actions within the body section whose values are moved to the
        ///     result OutputPins of the containing ConditionalNode after execution of the body.
        /// </summary>
        IEnumerable<OutputPin> bodyOutput { get; set; }

        /// <summary>
        ///     An OutputPin on an Action in the test section whose Boolean value determines
        ///     the result of the test.
        /// </summary>
        OutputPin decider { get; set; }
    }
} //end namespace Actions