///////////////////////////////////////////////////////////
//  ClearAssociationAction.cs
//  Implementation of the Class ClearAssociationAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:55
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.StructuredClassifiers;

namespace UML.Actions
{
    /// <summary>
    ///     A ClearAssociationAction is an Action that destroys all links of an Association
    ///     in which a particular object participates.
    /// </summary>
    public interface ClearAssociationAction : Action
    {
        /// <summary>
        ///     The Association to be cleared.
        /// </summary>
        Association association { get; set; }

        /// <summary>
        ///     The InputPin that gives the object whose participation in the Association is to
        ///     be cleared.
        /// </summary>
        InputPin Object { get; set; }
    }
} //end namespace Actions