///////////////////////////////////////////////////////////
//  ClearStructuralFeatureAction.cs
//  Implementation of the Class ClearStructuralFeatureAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:55
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Actions
{
    /// <summary>
    ///     A ClearStructuralFeatureAction is a StructuralFeatureAction that removes all
    ///     values of a StructuralFeature.
    /// </summary>
    public interface ClearStructuralFeatureAction : StructuralFeatureAction
    {
        /// <summary>
        ///     The OutputPin on which is put the input object as modified by the
        ///     ClearStructuralFeatureAction.
        /// </summary>
        OutputPin result { get; set; }
    }
} //end namespace Actions