///////////////////////////////////////////////////////////
//  ClearVariableAction.cs
//  Implementation of the Class ClearVariableAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:55
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Actions
{
    /// <summary>
    ///     A ClearVariableAction is a VariableAction that removes all values of a Variable.
    /// </summary>
    public interface ClearVariableAction : VariableAction
    {
    }
} //end namespace Actions