///////////////////////////////////////////////////////////
//  CreateObjectAction.cs
//  Implementation of the Class CreateObjectAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:57
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.Classification;

namespace UML.Actions
{
    /// <summary>
    ///     A CreateObjectAction is an Action that creates an instance of the specified
    ///     Classifier.
    /// </summary>
    public interface CreateObjectAction : Action
    {
        /// <summary>
        ///     The OutputPin on which the newly created object is placed.
        /// </summary>
        OutputPin result { get; set; }

        /// <summary>
        ///     The Classifier to be instantiated.
        /// </summary>
        Classifier classifier { get; set; }
    }
} //end namespace Actions