///////////////////////////////////////////////////////////
//  CreateLinkObjectAction.cs
//  Implementation of the Class CreateLinkObjectAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 21:59:57
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Actions
{
    /// <summary>
    ///     A CreateLinkObjectAction is a CreateLinkAction for creating link objects
    ///     (AssociationClasse instances).
    /// </summary>
    public interface CreateLinkObjectAction : CreateLinkAction
    {
        /// <summary>
        ///     The output pin on which the newly created link object is placed.
        /// </summary>
        OutputPin result { get; set; }
    }
} //end namespace Actions