///////////////////////////////////////////////////////////
//  ExpansionRegion.cs
//  Implementation of the Class ExpansionRegion
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:00
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;

namespace UML.Actions
{
    /// <summary>
    ///     An ExpansionRegion is a StructuredActivityNode that executes its content
    ///     multiple times corresponding to elements of input collection(s).
    /// </summary>
    public interface ExpansionRegion : StructuredActivityNode
    {
        /// <summary>
        ///     The mode in which the ExpansionRegion executes its contents. If parallel,
        ///     executions are concurrent. If iterative, executions are sequential. If stream,
        ///     a stream of values flows into a single execution.
        /// </summary>
        ExpansionKind mode { get; set; }

        /// <summary>
        ///     The ExpansionNodes that form the output collections of the ExpansionRegion.
        /// </summary>
        IEnumerable<ExpansionNode> outputElement { get; set; }

        /// <summary>
        ///     The ExpansionNodes that hold the input collections for the ExpansionRegion.
        /// </summary>
        ExpansionNode inputElement { get; set; }
    }
} //end namespace Actions