///////////////////////////////////////////////////////////
//  ExpansionNode.cs
//  Implementation of the Class ExpansionNode
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:00
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.Activities;

namespace UML.Actions
{
    /// <summary>
    ///     An ExpansionNode is an ObjectNode used to indicate a collection input or output
    ///     for an ExpansionRegion. A collection input of an ExpansionRegion contains a
    ///     collection that is broken into its individual elements inside the region, whose
    ///     content is executed once per element. A collection output of an ExpansionRegion
    ///     combines individual elements produced by the execution of the region into a
    ///     collection for use outside the region.
    /// </summary>
    public interface ExpansionNode : ObjectNode
    {
        /// <summary>
        ///     The ExpansionRegion for which the ExpansionNode is an output.
        /// </summary>
        ExpansionRegion regionAsOutput { get; set; }

        /// <summary>
        ///     The ExpansionRegion for which the ExpansionNode is an input.
        /// </summary>
        ExpansionRegion regionAsInput { get; set; }
    }
} //end namespace Actions