///////////////////////////////////////////////////////////
//  InputPin.cs
//  Implementation of the Class InputPin
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:03
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Actions
{
    /// <summary>
    ///     An InputPin is a Pin that holds input values to be consumed by an Action.
    /// </summary>
    public interface InputPin : Pin
    {
    }
} //end namespace Actions