///////////////////////////////////////////////////////////
//  InvocationAction.cs
//  Implementation of the Class InvocationAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:04
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using UML.StructuredClassifiers;

namespace UML.Actions
{
    /// <summary>
    ///     InvocationAction is an class for the various actions that request
    ///     Behavior invocation.
    /// </summary>
    public interface InvocationAction : Action
    {
        /// <summary>
        ///     For CallOperationActions, SendSignalActions, and SendObjectActions, an optional
        ///     Port of the target object through which the invocation request is sent.
        /// </summary>
        Port onPort { get; set; }

        /// <summary>
        ///     The InputPins that provide the argument values passed in the invocation request.
        /// </summary>
        IEnumerable<InputPin> argument { get; set; }
    }
} //end namespace Actions