///////////////////////////////////////////////////////////
//  LinkEndDestructionData.cs
//  Implementation of the Class LinkEndDestructionData
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:05
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Actions
{
    /// <summary>
    ///     LinkEndDestructionData is LinkEndData used to provide values for one end of a
    ///     link to be destroyed by a DestroyLinkAction.
    /// </summary>
    public interface LinkEndDestructionData : LinkEndData
    {
        /// <summary>
        ///     Specifies whether to destroy duplicates of the value in nonunique Association
        ///     ends.
        /// </summary>
        bool isDestroyDuplicates { get; set; }

        /// <summary>
        ///     The InputPin that provides the position of an existing link to be destroyed in
        ///     an ordered, nonunique Association end. The type of the destroyAt InputPin is
        ///     UnlimitedNatural, but the value cannot be zero or unlimited.
        /// </summary>
        InputPin destroyAt { get; set; }

        /// <summary>
        ///     Adds the destroyAt InputPin (if any) to the set of all Pins.
        /// </summary>
        /// <param name="result"></param>
        InputPin allPins(InputPin result);
    }
} //end namespace Actions