///////////////////////////////////////////////////////////
//  LinkEndData.cs
//  Implementation of the Class LinkEndData
//  Generated by Enterprise Architect
//  Created on:      31-ÿíâ-2019 22:00:05
//  Original author: Àíäðåé
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using UML.Classification;
using UML.CommonStructure;

namespace UML.Actions
{
    /// <summary>
    ///     LinkEndData is an Element that identifies on end of a link to be read or
    ///     written by a LinkAction. As a link (that is not a link object) cannot be passed
    ///     as a runtime value to or from an Action, it is instead identified by its end
    ///     objects and qualifier values, if any. A LinkEndData instance provides these
    ///     values for a single Association end.
    /// </summary>
    public interface LinkEndData : Element
    {
        /// <summary>
        ///     A set of QualifierValues used to provide values for the qualifiers of the end.
        /// </summary>
        IEnumerable<QualifierValue> qualifier { get; set; }

        /// <summary>
        ///     The Association end for which this LinkEndData specifies values.
        /// </summary>
        Property end { get; set; }

        /// <summary>
        ///     The InputPin that provides the specified value for the given end. This InputPin
        ///     is omitted if the LinkEndData specifies the "open" end for a ReadLinkAction.
        /// </summary>
        InputPin value { get; set; }

        /// <summary>
        ///     Returns all the InputPins referenced by this LinkEndData. By default this
        ///     includes the value and qualifier InputPins, but subclasses may override the
        ///     operation to add other InputPins.
        /// </summary>
        /// <param name="result"></param>
        InputPin allPins(InputPin result);
    }
} //end namespace Actions