///////////////////////////////////////////////////////////
//  LinkAction.cs
//  Implementation of the Class LinkAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:05
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using UML.StructuredClassifiers;

namespace UML.Actions
{
    /// <summary>
    ///     LinkAction is an class for all Actions that identify the links to be
    ///     acted on using LinkEndData.
    /// </summary>
    public interface LinkAction : Action
    {
        /// <summary>
        ///     The LinkEndData identifying the values on the ends of the links acting on by
        ///     this LinkAction.
        /// </summary>
        IEnumerable<LinkEndData> endData { get; set; }

        /// <summary>
        ///     InputPins used by the LinkEndData of the LinkAction.
        /// </summary>
        InputPin inputValue { get; set; }

        /// <summary>
        ///     Returns the Association acted on by this LinkAction.
        /// </summary>
        /// <param name="result"></param>
        Association association(Association result);
    }
} //end namespace Actions