///////////////////////////////////////////////////////////
//  OpaqueAction.cs
//  Implementation of the Class OpaqueAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:08
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;

namespace UML.Actions
{
    /// <summary>
    ///     An OpaqueAction is an Action whose functionality is not specified within UML.
    /// </summary>
    public interface OpaqueAction : Action
    {
        /// <summary>
        ///     Provides a textual specification of the functionality of the Action, in one or
        ///     more languages other than UML.
        /// </summary>
        string body { get; set; }

        /// <summary>
        ///     If provided, a specification of the language used for each of the body Strings.
        /// </summary>
        string language { get; set; }

        /// <summary>
        ///     The InputPins providing inputs to the OpaqueAction.
        /// </summary>
        IEnumerable<InputPin> inputValue { get; set; }

        /// <summary>
        ///     The OutputPins on which the OpaqueAction provides outputs.
        /// </summary>
        IEnumerable<OutputPin> outputValue { get; set; }
    }
} //end namespace Actions