///////////////////////////////////////////////////////////
//  OutputPin.cs
//  Implementation of the Class OutputPin
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:08
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Actions
{
    /// <summary>
    ///     An OutputPin is a Pin that holds output values produced by an Action.
    /// </summary>
    public interface OutputPin : Pin
    {
    }
} //end namespace Actions