///////////////////////////////////////////////////////////
//  QualifierValue.cs
//  Implementation of the Class QualifierValue
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:11
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.Classification;
using UML.CommonStructure;

namespace UML.Actions
{
    /// <summary>
    ///     A QualifierValue is an Element that is used as part of LinkEndData to provide
    ///     the value for a single qualifier of the end given by the LinkEndData.
    /// </summary>
    public interface QualifierValue : Element
    {
        /// <summary>
        ///     The InputPin from which the specified value for the qualifier is taken.
        /// </summary>
        InputPin value { get; set; }

        /// <summary>
        ///     The qualifier Property for which the value is to be specified.
        /// </summary>
        Property qualifier { get; set; }
    }
} //end namespace Actions