///////////////////////////////////////////////////////////
//  RaiseExceptionAction.cs
//  Implementation of the Class RaiseExceptionAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:11
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Actions
{
    /// <summary>
    ///     A RaiseExceptionAction is an Action that causes an exception to occur. The
    ///     input value becomes the exception object.
    /// </summary>
    public interface RaiseExceptionAction : Action
    {
        /// <summary>
        ///     An InputPin whose value becomes the exception object.
        /// </summary>
        InputPin exception { get; set; }
    }
} //end namespace Actions