///////////////////////////////////////////////////////////
//  ReadSelfAction.cs
//  Implementation of the Class ReadSelfAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:11
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Actions
{
    /// <summary>
    ///     A ReadSelfAction is an Action that retrieves the context object of the Behavior
    ///     execution within which the ReadSelfAction execution is taking place.
    /// </summary>
    public interface ReadSelfAction : Action
    {
        /// <summary>
        ///     The OutputPin on which the context object is placed.
        /// </summary>
        OutputPin result { get; set; }
    }
} //end namespace Actions