///////////////////////////////////////////////////////////
//  ReadLinkObjectEndAction.cs
//  Implementation of the Class ReadLinkObjectEndAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:11
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.Classification;

namespace UML.Actions
{
    /// <summary>
    ///     A ReadLinkObjectEndAction is an Action that retrieves an end object from a link
    ///     object.
    /// </summary>
    public interface ReadLinkObjectEndAction : Action
    {
        /// <summary>
        ///     The OutputPin where the result value is placed.
        /// </summary>
        OutputPin result { get; set; }

        /// <summary>
        ///     The Association end to be read.
        /// </summary>
        Property end { get; set; }

        /// <summary>
        ///     The input pin from which the link object is obtained.
        /// </summary>
        InputPin Object { get; set; }
    }
} //end namespace Actions