///////////////////////////////////////////////////////////
//  ReadVariableAction.cs
//  Implementation of the Class ReadVariableAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:11
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Actions
{
    /// <summary>
    ///     A ReadVariableAction is a VariableAction that retrieves the values of a
    ///     Variable.
    /// </summary>
    public interface ReadVariableAction : VariableAction
    {
        /// <summary>
        ///     The OutputPin on which the result values are placed.
        /// </summary>
        OutputPin result { get; set; }
    }
} //end namespace Actions