///////////////////////////////////////////////////////////
//  ReadStructuralFeatureAction.cs
//  Implementation of the Class ReadStructuralFeatureAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:11
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Actions
{
    /// <summary>
    ///     A ReadStructuralFeatureAction is a StructuralFeatureAction that retrieves the
    ///     values of a StructuralFeature.
    /// </summary>
    public interface ReadStructuralFeatureAction : StructuralFeatureAction
    {
        /// <summary>
        ///     The OutputPin on which the result values are placed.
        /// </summary>
        OutputPin result { get; set; }
    }
} //end namespace Actions