///////////////////////////////////////////////////////////
//  ReadLinkAction.cs
//  Implementation of the Class ReadLinkAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:11
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.Classification;

namespace UML.Actions
{
    /// <summary>
    ///     A ReadLinkAction is a LinkAction that navigates across an Association to
    ///     retrieve the objects on one end.
    /// </summary>
    public interface ReadLinkAction : LinkAction
    {
        /// <summary>
        ///     The OutputPin on which the objects retrieved from the "open" end of those links
        ///     whose values on other ends are given by the endData.
        /// </summary>
        OutputPin result { get; set; }

        /// <summary>
        ///     Returns the ends corresponding to endData with no value InputPin. (A well-
        ///     formed ReadLinkAction is constrained to have only one of these.)
        /// </summary>
        /// <param name="result"></param>
        Property openEnd(Property result);
    }
} //end namespace Actions