///////////////////////////////////////////////////////////
//  ReadIsClassifiedObjectAction.cs
//  Implementation of the Class ReadIsClassifiedObjectAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:11
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.Classification;

namespace UML.Actions
{
    /// <summary>
    ///     A ReadIsClassifiedObjectAction is an Action that determines whether an object
    ///     is classified by a given Classifier.
    /// </summary>
    public interface ReadIsClassifiedObjectAction : Action
    {
        /// <summary>
        ///     Indicates whether the input object must be directly classified by the given
        ///     Classifier or whether it may also be an instance of a specialization of the
        ///     given Classifier.
        /// </summary>
        bool isDirect { get; set; }

        /// <summary>
        ///     The InputPin that holds the object whose classification is to be tested.
        /// </summary>
        InputPin Object { get; set; }

        /// <summary>
        ///     The OutputPin that holds the Boolean result of the test.
        /// </summary>
        OutputPin result { get; set; }

        /// <summary>
        ///     The Classifier against which the classification of the input object is tested.
        /// </summary>
        Classifier classifier { get; set; }
    }
} //end namespace Actions