///////////////////////////////////////////////////////////
//  ReduceAction.cs
//  Implementation of the Class ReduceAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:12
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.CommonBehavior;

namespace UML.Actions
{
    /// <summary>
    ///     A ReduceAction is an Action that reduces a collection to a single value by
    ///     repeatedly combining the elements of the collection using a reducer Behavior.
    /// </summary>
    public interface ReduceAction : Action
    {
        /// <summary>
        ///     Indicates whether the order of the input collection should determine the order
        ///     in which the reducer Behavior is applied to its elements.
        /// </summary>
        bool isOrdered { get; set; }

        /// <summary>
        ///     The output pin on which the result value is placed.
        /// </summary>
        OutputPin result { get; set; }

        /// <summary>
        ///     A Behavior that is repreatedly applied to two elements of the input collection
        ///     to produce a value that is of the same type as elements of the collection.
        /// </summary>
        Behavior reducer { get; set; }

        /// <summary>
        ///     The InputPin that provides the collection to be reduced.
        /// </summary>
        InputPin collection { get; set; }
    }
} //end namespace Actions