///////////////////////////////////////////////////////////
//  RemoveVariableValueAction.cs
//  Implementation of the Class RemoveVariableValueAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:13
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Actions
{
    /// <summary>
    ///     A RemoveVariableValueAction is a WriteVariableAction that removes values from a
    ///     Variables.
    /// </summary>
    public interface RemoveVariableValueAction : WriteVariableAction
    {
        /// <summary>
        ///     Specifies whether to remove duplicates of the value in nonunique Variables.
        /// </summary>
        bool isRemoveDuplicates { get; set; }

        /// <summary>
        ///     An InputPin that provides the position of an existing value to remove in
        ///     ordered, nonunique Variables. The type of the removeAt InputPin is
        ///     UnlimitedNatural, but the value cannot be zero or unlimited.
        /// </summary>
        InputPin removeAt { get; set; }
    }
} //end namespace Actions