///////////////////////////////////////////////////////////
//  SendSignalAction.cs
//  Implementation of the Class SendSignalAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:13
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.SimpleClassifiers;

namespace UML.Actions
{
    /// <summary>
    ///     A SendSignalAction is an InvocationAction that creates a Signal instance and
    ///     transmits it to the target object. Values from the argument InputPins are used
    ///     to provide values for the attributes of the Signal. The requestor continues
    ///     execution immediately after the Signal instance is sent out and cannot receive
    ///     reply values.
    /// </summary>
    public interface SendSignalAction : InvocationAction
    {
        /// <summary>
        ///     The InputPin that provides the target object to which the Signal instance is
        ///     sent.
        /// </summary>
        InputPin target { get; set; }

        /// <summary>
        ///     The Signal whose instance is transmitted to the target.
        /// </summary>
        Signal signal { get; set; }
    }
} //end namespace Actions