///////////////////////////////////////////////////////////
//  SendObjectAction.cs
//  Implementation of the Class SendObjectAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:13
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Actions
{
    /// <summary>
    ///     A SendObjectAction is an InvocationAction that transmits an input object to the
    ///     target object, which is handled as a request message by the target object. The
    ///     requestor continues execution immediately after the object is sent out and
    ///     cannot receive reply values.
    /// </summary>
    public interface SendObjectAction : InvocationAction
    {
        /// <summary>
        ///     The target object to which the object is sent.
        /// </summary>
        InputPin target { get; set; }

        /// <summary>
        ///     The request object, which is transmitted to the target object. The object may
        ///     be copied in transmission, so identity might not be preserved.
        /// </summary>
        InputPin request { get; set; }
    }
} //end namespace Actions