///////////////////////////////////////////////////////////
//  SequenceNode.cs
//  Implementation of the Class SequenceNode
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:13
//  Original author: Андрей
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using UML.Activities;

namespace UML.Actions
{
    /// <summary>
    ///     A SequenceNode is a StructuredActivityNode that executes a sequence of
    ///     ExecutableNodes in order.
    /// </summary>
    public interface SequenceNode : StructuredActivityNode
    {
        /// <summary>
        ///     The ordered set of ExecutableNodes to be sequenced.
        /// </summary>
        IEnumerable<ExecutableNode> executableNode { get; set; }
    }
} //end namespace Actions