///////////////////////////////////////////////////////////
//  StartObjectBehaviorAction.cs
//  Implementation of the Class StartObjectBehaviorAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:14
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.Classification;
using UML.CommonBehavior;

namespace UML.Actions
{
    /// <summary>
    ///     A StartObjectBehaviorAction is an InvocationAction that starts the execution
    ///     either of a directly instantiated Behavior or of the classifierBehavior of an
    ///     object. Argument values may be supplied for the input Parameters of the
    ///     Behavior. If the Behavior is invoked synchronously, then output values may be
    ///     obtained for output Parameters.
    /// </summary>
    public interface StartObjectBehaviorAction : CallAction
    {
        /// <summary>
        ///     An InputPin that holds the object that is either a Behavior to be started or
        ///     has a classifierBehavior to be started.
        /// </summary>
        InputPin Object { get; set; }

        /// <summary>
        ///     If the type of the object InputPin is a Behavior, then that Behavior. Otherwise,
        ///     if the type of the object InputPin is a BehavioredClassifier, then the
        ///     classifierBehavior of that BehavioredClassifier.
        /// </summary>
        /// <param name="result"></param>
        Behavior behavior(Behavior result);

        /// <summary>
        ///     Return the in and inout ownedParameters of the Behavior being called.
        /// </summary>
        /// <param name="result"></param>
        Parameter inputParameters(Parameter result);

        /// <summary>
        ///     Return the inout, out and return ownedParameters of the Behavior being called.
        /// </summary>
        /// <param name="result"></param>
        Parameter outputParameters(Parameter result);
    }
} //end namespace Actions