///////////////////////////////////////////////////////////
//  TestIdentityAction.cs
//  Implementation of the Class TestIdentityAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:15
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Actions
{
    /// <summary>
    ///     A TestIdentityAction is an Action that tests if two values are identical
    ///     objects.
    /// </summary>
    public interface TestIdentityAction : Action
    {
        /// <summary>
        ///     The OutputPin whose Boolean value indicates whether the two input objects are
        ///     identical.
        /// </summary>
        OutputPin result { get; set; }

        /// <summary>
        ///     The OutputPin on which the second input object is placed.
        /// </summary>
        InputPin second { get; set; }

        /// <summary>
        ///     The InputPin on which the first input object is placed.
        /// </summary>
        InputPin first { get; set; }
    }
} //end namespace Actions