///////////////////////////////////////////////////////////
//  UnmarshallAction.cs
//  Implementation of the Class UnmarshallAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:17
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.Classification;

namespace UML.Actions
{
    /// <summary>
    ///     An UnmarshallAction is an Action that retrieves the values of the
    ///     StructuralFeatures of an object and places them on OutputPins.
    /// </summary>
    public interface UnmarshallAction : Action
    {
        /// <summary>
        ///     The InputPin that gives the object to be unmarshalled.
        /// </summary>
        InputPin Object { get; set; }

        /// <summary>
        ///     The type of the object to be unmarshalled.
        /// </summary>
        Classifier unmarshallType { get; set; }

        /// <summary>
        ///     The OutputPins on which are placed the values of the StructuralFeatures of the
        ///     input object.
        /// </summary>
        OutputPin result { get; set; }
    }
} //end namespace Actions