///////////////////////////////////////////////////////////
//  ValueSpecificationAction.cs
//  Implementation of the Class ValueSpecificationAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:18
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.Values;

namespace UML.Actions
{
    /// <summary>
    ///     A ValueSpecificationAction is an Action that evaluates a ValueSpecification and
    ///     provides a result.
    /// </summary>
    public interface ValueSpecificationAction : Action
    {
        /// <summary>
        ///     The ValueSpecification to be evaluated.
        /// </summary>
        ValueSpecification value { get; set; }

        /// <summary>
        ///     The OutputPin on which the result value is placed.
        /// </summary>
        OutputPin result { get; set; }
    }
} //end namespace Actions