///////////////////////////////////////////////////////////
//  ValuePin.cs
//  Implementation of the Class ValuePin
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:17
//  Original author: Андрей
///////////////////////////////////////////////////////////

using UML.Values;

namespace UML.Actions
{
    /// <summary>
    ///     A ValuePin is an InputPin that provides a value by evaluating a
    ///     ValueSpecification.
    /// </summary>
    public interface ValuePin : InputPin
    {
        /// <summary>
        ///     The ValueSpecification that is evaluated to obtain the value that the ValuePin
        ///     will provide.
        /// </summary>
        ValueSpecification value { get; set; }
    }
} //end namespace Actions