///////////////////////////////////////////////////////////
//  WriteLinkAction.cs
//  Implementation of the Class WriteLinkAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:18
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Actions
{
    /// <summary>
    ///     WriteLinkAction is an class for LinkActions that create and destroy
    ///     links.
    /// </summary>
    public interface WriteLinkAction : LinkAction
    {
    }
} //end namespace Actions