///////////////////////////////////////////////////////////
//  WriteStructuralFeatureAction.cs
//  Implementation of the Class WriteStructuralFeatureAction
//  Generated by Enterprise Architect
//  Created on:      31-янв-2019 22:00:18
//  Original author: Андрей
///////////////////////////////////////////////////////////

namespace UML.Actions
{
    /// <summary>
    ///     WriteStructuralFeatureAction is an class for StructuralFeatureActions
    ///     that change StructuralFeature values.
    /// </summary>
    public interface WriteStructuralFeatureAction : StructuralFeatureAction
    {
        /// <summary>
        ///     The InputPin that provides the value to be added or removed from the
        ///     StructuralFeature.
        /// </summary>
        InputPin value { get; set; }

        /// <summary>
        ///     The OutputPin on which is put the input object as modified by the
        ///     WriteStructuralFeatureAction.
        /// </summary>
        OutputPin result { get; set; }
    }
} //end namespace Actions